services:
  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/discharge_list_db
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: discharge_list_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    env_file:
      - frontend/.env.local
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3006:3006" # Map frontend to localhost:3006
    expose:
      - 3006

volumes:
  postgres_data:
