"""initial migration

Revision ID: acef4c75dfab
Revises: 1b6fe5ea5fcd
Create Date: 2025-01-27 09:59:38.684968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acef4c75dfab'
down_revision: Union[str, None] = '1b6fe5ea5fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
